name: deploy to github pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} 

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: '16.20.2'

      - name: Install and build
        run: |
          npm install
          npm run build

      - name: Publish artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
